function Nike() {
    const products = [
        { img: "./src/assets/nike/2 Nike/nike1.jpg", title: "Nike", model: "Modelo Exclusivo", price: "¢ 33.000" },
        { img: "./src/assets/nike/2 Nike/nike2.jpg", title: "Nike ", model: "Edición Limitada", price: "¢ 33.000" },
        { img: "./src/assets/nike/2 Nike/nike3.jpg", title: "Nike ", model: "Super Ligero", price: "¢ 30.000" },
        { img: "./src/assets/nike/2 Nike/nike4.jpg", title: "Nike ", model: "Super Ligero", price: "¢ 30.000" },
        { img: "./src/assets/nike/2 Nike/nike5.jpg", title: "Nike ", model: "Super Ligero", price: "¢ 33.000" },
        { img: "./src/assets/nike/2 Nike/nike6.jpg", title: "Nike ", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike7.jpg", title: "Nike ", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike8.jpg", title: "Nike ", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike9.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike10.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike11.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike12.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike13.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike14.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike15.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike16.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike17.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike18.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike19.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike20.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike21.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike22.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike23.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike24.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike25.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike26.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike27.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike28.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike29.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike30.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike31.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike32.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike33.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike34.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike35.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike36.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike37.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike38.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike39.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike40.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike41.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike42.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike43.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike44.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike45.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike46.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike47.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike48.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike49.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike50.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike51.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike52.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike53.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike54.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike55.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike56.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike57.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike58.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike59.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike60.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike61.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike62.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike63.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike64.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike65.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike66.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike67.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike68.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike69.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike70.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike71.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike72.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike73.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike74.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike75.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike76.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike77.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike78.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike79.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike80.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike81.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike82.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike83.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike84.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike85.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike86.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike87.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike88.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike89.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike90.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike91.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike92.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike93.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike94.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike95.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike96.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike97.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike98.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike99.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike100.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike101.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike102.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike103.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike104.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike105.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike106.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike107.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike108.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike109.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike110.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike111.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike112.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike113.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike114.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike115.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike116.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike117.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike118.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike119.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike120.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike121.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike122.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike123.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike124.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike125.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike126.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike127.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike128.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike129.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike130.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike131.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike132.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike133.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike134.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike135.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike136.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike137.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike138.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike139.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike140.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike141.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike142.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike143.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike144.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike145.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike146.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike147.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },
        { img: "./src/assets/nike/2 Nike/nike148.jpg", title: "Nike", model: "Super Ligero", price: "¢ 45.000" },




    ];

    return (
        <div className="grid grid-cols-4 sm:grid-cols-1 lg:grid-cols-1 gap-8 mt-10 p-4">
            {products.map((product, index) => (
                <div key={index} className="relative z-10 nike-container p-8 bg-white shadow-2xl rounded-3xl overflow-hidden w-80 h-96 flex flex-col items-center justify-between transition-transform duration-300 hover:scale-105">
                    <div className="relative w-full h-3/4 overflow-hidden rounded-2xl">
                        <img
                            className="w-full h-full object-cover cursor-pointer transition-transform duration-300 hover:scale-125"
                            src={product.img}
                            alt={product.title}
                        />
                    </div>
                    <div className="w-full text-center p-4 bg-gray-50 rounded-b-3xl">
                        <p className="text-2xl font-extrabold text-gray-900">{product.title}</p>
                        <p className="text-lg text-gray-500">{product.model}</p>
                        <p className="mt-2 text-xl font-bold text-red-500">{product.price}</p>
                    </div>
                </div>
            ))}
        </div>
    );
};

export default Nike;
