import React from "react";

function Bolso() {
    const products = [
        { img: "/BOLSOS/BLS1.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS2.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS3.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS4.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS5.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS6.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS7.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS8.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS9.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS10.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS11.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 19.500" },
        { img: "/BOLSOS/BLS12.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS13.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS14.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS15.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 21.000" },
        { img: "/BOLSOS/BLS16.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS17.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS18.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS19.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS20.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS21.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS22.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS23.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS24.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS25.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS26.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS27.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS28.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS29.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS30.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS31.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS32.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS33.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS34.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS35.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS36.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS37.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS38.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS39.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS40.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS41.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS42.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS43.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS44.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS45.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS46.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS47.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS48.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS49.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS50.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS51.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS52.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS53.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS54.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS55.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS56.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS57.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS58.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS59.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS60.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS61.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS62.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS63.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS64.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS65.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS66.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS67.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS68.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS69.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS70.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS71.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS72.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS73.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS74.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS75.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS76.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS77.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS78.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS79.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS80.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS81.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS82.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS83.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS84.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS85.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS86.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS87.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS88.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS89.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS90.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS91.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS92.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS93.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS94.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS95.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS96.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS97.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS98.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS99.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS100.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS101.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 19.500" },
        { img: "/BOLSOS/BLS102.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 19.500" },
        { img: "/BOLSOS/BLS103.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS104.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS105.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS106.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS107.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 21.000" },
        { img: "/BOLSOS/BLS108.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 19.500" },
        { img: "/BOLSOS/BLS109.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS110.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS111.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS112.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS113.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS114.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS115.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS116.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS117.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS118.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS119.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS120.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS121.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS122.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS123.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS124.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS125.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS126.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS127.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS128.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS129.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS130.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS131.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS132.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS133.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS134.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS135.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS136.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS137.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS138.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS139.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS140.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS141.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS142.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS143.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS144.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS145.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS146.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 21.000" },
        { img: "/BOLSOS/BLS147.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS148.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS149.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS150.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS151.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS152.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS153.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS154.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 25.500" },
        { img: "/BOLSOS/BLS155.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
        { img: "/BOLSOS/BLS156.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS157.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 27.000" },
        { img: "/BOLSOS/BLS158.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 24.000" },
        { img: "/BOLSOS/BLS159.jpg", title: "Bolso", model: "Modelo Exclusivo", price: "¢ 30.000" },
          

    ];

    return (
        <div className="">
            <div className="grid grid-cols-4 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-6">
                {products.map((product, index) => (
                    <div
                        key={index}
                        className="bg-white shadow-lg border rounded-2xl shadow-lg overflow-hidden hover:shadow-xl transition-transform duration-300 hover:scale-105"
                    >
                        <img
                            src={product.img}
                            alt={product.title}
                            className="w-full h-[500px] object-cover"
                        />
                        <div className="p-4">
                            <h3 className="text-lg font-semibold">{product.title}</h3>
                            <p className="text-gray-600">{product.model}</p>
                            <p className="text-sm text-gray-500">{product.size}</p>
                            <p className="text-red-600 font-bold">{product.price}</p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Bolso;